# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.148.1/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.12, 3.11, 3.10
# ARG VARIANT="3.12"
FROM mcr.microsoft.com/dotnet/sdk:5.0

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
